PackageIdentifier: Linus-Shyu.StarFetch
PackageVersion: 0.2.2
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Linus-Shyu/StarFetch_Core/releases/download/v0.2.2/starfetch-x86_64-pc-windows-msvc.zip
    InstallerSha256: 8ce31a9d378b4c206c7dddad413f86b426e7ab82bdaec3425851649832ab37bf
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: starfetch.exe
        PortableCommandAlias: starfetch
ManifestType: installer
ManifestVersion: 1.4.0
