PackageIdentifier: Linus-Shyu.StarFetch
PackageVersion: 0.2.3
InstallerType: zip
Scope: user
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Linus-Shyu/StarFetch_Core/releases/download/v0.2.3/starfetch-x86_64-pc-windows-msvc.zip
    InstallerSha256: FA37F5EC4A694905D95B194FCCC36F7BB67B6E414E9665091063F3F0DF00D635
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: starfetch.exe
        PortableCommandAlias: starfetch
ManifestType: installer
ManifestVersion: 1.10.0
